# Generated by Django 6.0.3 on 2026-05-12 09:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0027_settings_feedback_is_writable_and_more'),
        ('team', '0015_alter_team_coach_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerFeedback1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_score', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('collaboration_score', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('reliability_score', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Begründung')),
                ('reviewed_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_peer_feedback', to='app.student')),
                ('reviewing_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_peer_feedback', to='app.student')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
            ],
            options={
                'ordering': ('team__project_instance', 'reviewing_student', 'reviewed_student'),
                'constraints': [models.UniqueConstraint(fields=('team', 'reviewing_student', 'reviewed_student'), name='unique_peer_feedback')],
            },
        ),
    ]
