# Generated by Django 6.0.5 on 2026-06-03 11:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_settings_peer_feedback_1_is_visible_and_more'),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peerfeedback1',
            name='reason',
            field=models.TextField(default='', validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Begründung'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peerfeedback1',
            name='reviewed_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_peer_feedback_1', to='app.student'),
        ),
        migrations.AlterField(
            model_name='peerfeedback1',
            name='reviewing_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_peer_feedback_1', to='app.student'),
        ),
    ]
