# Generated by Django 5.2.5 on 2025-08-19 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.project')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_is_initial_contact', models.BooleanField(default=False)),
                ('score', models.FloatField(null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.project')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.student')),
            ],
            options={
                'ordering': ('project', '-student_is_initial_contact', 'student'),
            },
        ),
    ]
