# Generated by Django 4.2.5 on 2023-09-29 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.project')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.role')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.student')),
            ],
            options={
                'ordering': ('project', 'role', 'student'),
            },
        ),
    ]
