# Generated by Django 4.2.5 on 2023-09-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
