# Generated by Django 5.2.5 on 2025-08-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('project', 'role_new', 'student')},
        ),
        migrations.AddField(
            model_name='team',
            name='role_new',
            field=models.BooleanField(default=False),
        ),
    ]
