# Generated by Django 5.2.5 on 2025-08-18 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_team_options_team_role_new'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('project', 'student')},
        ),
        migrations.RemoveField(
            model_name='team',
            name='role',
        ),
        migrations.RemoveField(
            model_name='team',
            name='role_new',
        ),
    ]
