# Generated by Django 5.2.5 on 2025-08-19 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_project_instance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectinstance',
            options={'ordering': ('project', 'number')},
        ),
    ]
