# Generated by Django 5.2.5 on 2025-08-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_project_instances_and_more'),
        ('team', '0003_alter_projectinstance_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='projectinstance',
            constraint=models.UniqueConstraint(fields=('project', 'number'), name='unique_project_number'),
        ),
    ]
