# Generated by Django 6.0.3 on 2026-05-04 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_devsettings_max_runtime_alter_student_s_number'),
        ('team', '0004_projectinstance_unique_project_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_is_initial_contact', models.BooleanField(default=False)),
                ('score', models.FloatField(null=True)),
                ('project_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='team.projectinstance')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.student')),
            ],
            options={
                'ordering': ('project_instance', '-student_is_initial_contact', 'student'),
            },
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
