# Generated by Django 6.0.3 on 2026-05-04 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_teammember_delete_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ('team__project_instance', '-student_is_initial_contact', 'student')},
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='project_instance',
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_repository', models.URLField(blank=True, null=True, verbose_name='Link zum GitHub Repository')),
                ('url_project', models.URLField(blank=True, null=True, verbose_name='Link zum GitHub Project')),
                ('url_miro', models.URLField(blank=True, null=True, verbose_name='Link zum Miro Board')),
                ('project_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='team.projectinstance', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='team.team'),
        ),
    ]
