# Generated by Django 6.0.3 on 2026-05-04 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_alter_teammember_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('project_instance',)},
        ),
    ]
