# Generated by Django 6.0.3 on 2026-05-04 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_alter_team_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='project_instance',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, to='team.projectinstance', unique=True),
            preserve_default=False,
        ),
    ]
