# Generated by Django 6.0.3 on 2026-05-04 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_alter_team_project_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='project_instance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='team.projectinstance'),
        ),
    ]
