# Generated by Django 6.0.3 on 2026-05-04 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_alter_team_project_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, to='team.team'),
            preserve_default=False,
        ),
    ]
