# Generated by Django 6.0.3 on 2026-05-04 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0011_alter_teammember_options_remove_team_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, to='team.team'),
            preserve_default=False,
        ),
    ]
