# Generated by Django 6.0.3 on 2026-05-04 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0012_teammember_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ('team__project_instance', '-student_is_initial_contact', 'student')},
        ),
    ]
