# Generated by Django 6.0.3 on 2026-05-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0013_alter_teammember_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='coach_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail des Coaches'),
        ),
        migrations.AddField(
            model_name='team',
            name='coach_name',
            field=models.TextField(blank=True, null=True, verbose_name='Name des Coaches'),
        ),
    ]
