# Generated by Django 6.0.3 on 2026-05-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0014_team_coach_email_team_coach_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='coach_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name des Coaches'),
        ),
    ]
