# Generated by Django 4.2.5 on 2023-09-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_generated',
            field=models.BooleanField(default=False),
        ),
    ]
