[tool.ruff]
line-length = 120
indent-width = 4
preview = true

[tool.ruff.lint]
preview = true

[tool.ruff.format]
indent-style = "space"
preview = true

# [tool.basedpyright]
# typeCheckingMode = "standard"
## diagnosticMode = "workspace"
