# Set base image
FROM nginx:alpine

# Install nginx config
# DEACTIVATED: Use templates instead
# v1: overwrite
#COPY docker/nginx/default.conf /etc/nginx/conf.d
# v2: remove and copy
#RUN rm /etc/nginx/conf.d/default.conf
#COPY docker/nginx/default.conf /etc/nginx/conf.d
