# Generated by Django 5.2.5 on 2025-08-19 08:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teams_last_update', models.DateTimeField(blank=True, null=True, verbose_name='Zeitpunkt der letzten Teamänderung')),
                ('polls_last_update', models.DateTimeField(blank=True, null=True, verbose_name='Zeitpunkt der letzten Umfrageänderung')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects_is_visible', models.BooleanField(default=False, help_text='Wenn aktiv, sind die Projekte für die Studenten sichtbar.', verbose_name='Projekte anzeigen')),
                ('poll_is_visible', models.BooleanField(default=False, help_text='Wenn aktiv, ist der Fragebogen für die Studenten sichtbar.', verbose_name='Fragebogen anzeigen')),
                ('poll_is_writable', models.BooleanField(default=False, help_text='Wenn aktiv, kann der Fragebogen von den Studenten beantwortet bzw. geändert und abgesendet werden.', verbose_name='Fragebogen is ausfüllbar (schreibbar)')),
                ('teams_is_visible', models.BooleanField(default=False, help_text='Wenn aktiv, sind die Teams für die Studenten sichtbar. Solange die Teams sichtbar sind, können keine Teams generiert oder verändert werden!', verbose_name='Teams anzeigen')),
                ('team_min_member', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Mindestanzahl der Studenten je Team')),
                ('wings_are_out', models.BooleanField(default=False, help_text='Wenn aktiv, werden die Wirtschaftsingenieure (Wings) für Software Engineering II in den Teams nicht mehr angezeigt. Sie nehmen nur an SE I teil.', verbose_name='Wings für SE II in den Teams ausblenden')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_number', models.CharField(max_length=8, unique=True, verbose_name='Matrikelnummer')),
                ('first_name', models.CharField(max_length=255, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=255, verbose_name='Nachname')),
                ('study_program', models.CharField(choices=[('041', 'Informatik (041)'), ('042', 'Wirtschaftsinformatik (042)'), ('048', 'Verwaltungsinformatik (048)'), ('072', 'Wirtschaftsingenieurwesen (072)')], max_length=3, verbose_name='Studiengang')),
                ('is_active', models.BooleanField(default=True, help_text='Für Studenten die nicht mehr am Projekt teilnehmen, ist diese Option zu deaktivieren.', verbose_name='Nimmt am Projekt teil')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid2', models.CharField(help_text='Es sind nur Großbuchstaben von A bis Z erlaubt.', max_length=1, unique=True, validators=[django.core.validators.RegexValidator('[A-Z]')], verbose_name='ID')),
                ('type', models.CharField(choices=[('i', 'Intern'), ('e', 'Extern')], default=('i', 'Intern'), max_length=1, verbose_name='Art')),
                ('number', models.IntegerField(help_text='Art und Nummer ergeben eine eindeutige Projekt-ID (bspw. I4, E2)', verbose_name='Nummer')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Beschreibung')),
                ('technologies', models.CharField(blank=True, max_length=255, null=True, verbose_name='Technologien')),
                ('company', models.CharField(blank=True, help_text='Name der Firma, des Verein oder der Hochschule mit Fakultät', max_length=255, null=True, verbose_name='Auftraggeber')),
                ('contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kontakt')),
                ('url', models.URLField(blank=True, help_text='PDF-Link zu den Projektbescheibungen in Opal', null=True, verbose_name='Link zu weiteren Informationen')),
            ],
            options={
                'ordering': ('type', 'number'),
                'unique_together': {('type', 'number')},
            },
        ),
    ]
