# Generated by Django 5.2.5 on 2025-08-19 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='pid2',
            new_name='pid',
        ),
    ]
