# Generated by Django 4.2.6 on 2023-10-30 07:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teams_last_update', models.DateTimeField(blank=True, null=True)),
                ('polls_last_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='settings',
            name='poll_is_visible',
            field=models.BooleanField(default=False, verbose_name='Fragebogen anzeigen'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='poll_is_writable',
            field=models.BooleanField(default=False, help_text='Wenn aktiv, kann der Fragebogen beantwortet bzw. geändert und abgesendet werden.', verbose_name='Fragebogen is ausfüllbar (schreibbar)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='projects_is_visible',
            field=models.BooleanField(default=False, verbose_name='Projekte anzeigen'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='team_min_member',
            field=models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Mindestanzahl der Studenten je Team'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='teams_is_visible',
            field=models.BooleanField(default=False, help_text='Wenn aktiv, können keine Teams mehr generiert oder verändert werden!', verbose_name='Teams anzeigen'),
        ),
    ]
