# Generated by Django 5.2.5 on 2025-08-19 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_pid2_project_pid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('pid',)},
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='project',
            name='pid',
            field=models.CharField(help_text='Muss ein Großbuchstaben von A bis Z sein.', max_length=1, unique=True, validators=[django.core.validators.RegexValidator('[A-Z]')], verbose_name='PID'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='number',
        ),
        migrations.RemoveField(
            model_name='project',
            name='type',
        ),
    ]
