# Generated by Django 4.2.6 on 2023-10-30 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_meta_alter_settings_poll_is_visible_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meta',
            new_name='Info',
        ),
    ]
