# Generated by Django 5.0.1 on 2024-01-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_meta_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Nimmt am Projekt teil'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_number',
            field=models.CharField(max_length=8, unique=True, verbose_name='Matrikelnummer'),
        ),
        migrations.AlterField(
            model_name='student',
            name='study_program',
            field=models.CharField(choices=[('041', 'Informatik (041)'), ('042', 'Wirtschaftsinformatik (042)'), ('048', 'Verwaltungsinformatik (048)'), ('072', 'Wirtschaftsingenieurwesen (072)')], max_length=3, verbose_name='Studiengang'),
        ),
    ]
