# Generated by Django 5.2.5 on 2025-08-19 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_project_options_alter_project_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='instances',
            field=models.IntegerField(default=1, help_text='Anzahl der maximalen Projektinstanzen (1-99)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Anzahl'),
        ),
    ]
