# Generated by Django 5.0.1 on 2024-01-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_student_is_active_alter_student_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='polls_last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Zeitpunkt der letzten Umfrageänderung'),
        ),
        migrations.AlterField(
            model_name='info',
            name='teams_last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Zeitpunkt der letzten Teamänderung'),
        ),
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Auftraggeber (Firmenname)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kontakt'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='number',
            field=models.IntegerField(help_text='Art und Nummer ergeben eine eindeutige Projekt-ID (bspw. I4, E2)', verbose_name='Nummer'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Technologien'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('i', 'Intern'), ('e', 'Extern')], default=('i', 'Intern'), max_length=1, verbose_name='Art'),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Link zu weiteren Informationen (PDF)'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Für Studenten die nicht mehr am Projekt teilnehmen, ist diese Option zu deaktivieren.', verbose_name='Nimmt am Projekt teil'),
        ),
    ]
