# Generated by Django 5.2.5 on 2025-08-19 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_project_instances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='instances',
            field=models.IntegerField(blank=True, help_text='Anzahl der maximalen Projektinstanzen (1-99)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Instanzen'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pid',
            field=models.CharField(help_text='Muss ein Großbuchstaben von A bis Z sein', max_length=1, unique=True, validators=[django.core.validators.RegexValidator('[A-Z]')], verbose_name='ID'),
        ),
    ]
