# Generated by Django 5.0.1 on 2024-01-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_info_polls_last_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.CharField(blank=True, help_text='Name der Firma, des Verein oder der Hochschule mit Fakultät', max_length=255, null=True, verbose_name='Auftraggeber'),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, help_text='PDF-Link zu den Projektbescheibungen in Opal', null=True, verbose_name='Link zu weiteren Informationen'),
        ),
    ]
