# Generated by Django 5.2.5 on 2025-08-19 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_project_instances_alter_project_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='project_instances',
            field=models.IntegerField(default=4, help_text='Anzahl muss zwischen 1 und 99 liegen', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Standardanzahl der Projektinstanzen'),
        ),
    ]
