# Generated by Django 5.0.1 on 2024-01-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_project_company_alter_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='poll_is_visible',
            field=models.BooleanField(default=False, help_text='Wenn aktiv, kann der Fragebogen von den Studenten angeschaut werden.', verbose_name='Fragebogen anzeigen'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='poll_is_writable',
            field=models.BooleanField(default=False, help_text='Wenn aktiv, kann der Fragebogen von den Studenten beantwortet bzw. geändert und abgesendet werden.', verbose_name='Fragebogen is ausfüllbar (schreibbar)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='projects_is_visible',
            field=models.BooleanField(default=False, help_text='Wenn aktiv, können die Projekte von den Studenten angeschaut werden.', verbose_name='Projekte anzeigen'),
        ),
    ]
