# Generated by Django 5.0.1 on 2024-01-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_settings_poll_is_visible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='poll_is_visible',
            field=models.BooleanField(default=False, help_text='Wenn aktiv, ist der Fragebogen für die Studenten sichtbar.', verbose_name='Fragebogen anzeigen'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='projects_is_visible',
            field=models.BooleanField(default=False, help_text='Wenn aktiv, sind die Projekte für die Studenten sichtbar.', verbose_name='Projekte anzeigen'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='teams_is_visible',
            field=models.BooleanField(default=False, help_text='Wenn aktiv, sind die Teams für die Studenten sichtbar. Solange die Teams sichtbar sind, können keine Teams generiert oder verändert werden!', verbose_name='Teams anzeigen'),
        ),
    ]
