# Generated by Django 5.2.5 on 2025-08-19 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_settings_project_instances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='instances',
            field=models.IntegerField(blank=True, help_text='Leer für Standardanzahl aus den Einstellungen oder Anzahl der maximalen Projektinstanzen (1-99)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Instanzen'),
        ),
    ]
