# Generated by Django 5.2.5 on 2025-08-19 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_project_instances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='team_min_member',
            field=models.IntegerField(default=6, help_text='Anzahl muss zwischen 1 und 20 liegen.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Mindestanzahl der Studenten je Team'),
        ),
    ]
