# Generated by Django 5.0.1 on 2024-02-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_settings_wings_are_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='wings_are_out',
            field=models.BooleanField(default=False, help_text='Wenn aktiv, werden die Wirtschaftsingenieure (Wings) für Software Engineering II in den Teams nicht mehr angezeigt. Sie nehmen nur an SE I teil.', verbose_name='Wings für SE II in den Teams ausblenden'),
        ),
    ]
