# Generated by Django 5.2.5 on 2025-08-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_settings_team_min_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='use_random_poll_defaults',
            field=models.BooleanField(default=False, help_text='Wenn aktiv, werden leere Fragebögen nicht mit neutralen (3) Antworten, sondern mit zufälligen (1-5) ausgefüllt.', verbose_name='Zufällige Anworten verwenden'),
        ),
        migrations.AlterField(
            model_name='student',
            name='study_program',
            field=models.CharField(choices=[('041', 'Informatik (041, AI)'), ('042', 'Wirtschaftsinformatik (042, WI)'), ('048', 'Verwaltungsinformatik (048, VI)'), ('072', 'Wirtschaftsingenieurwesen (072, WIng)')], max_length=3, verbose_name='Studiengang'),
        ),
    ]
