# Generated by Django 5.2.5 on 2025-08-18 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_settings_wings_are_out'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
