# Generated by Django 5.2.5 on 2025-08-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_settings_use_random_poll_defaults_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='use_random_poll_defaults',
            field=models.BooleanField(default=False, help_text='Wenn aktiv, werden leere Fragebögen nicht mit neutralen Antworten (3), sondern mit zufälligen Anworten (1-5) ausgefüllt.', verbose_name='Zufällige Anworten für leere Fragebögen generieren'),
        ),
    ]
