# Generated by Django 5.2.5 on 2025-08-20 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_settings_use_random_poll_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='instances',
            field=models.PositiveIntegerField(blank=True, help_text='Leer für Standardanzahl aus den Einstellungen oder Angabe der individuellen Anzahl der maximalen Projektinstanzen (1-99)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Instanzen'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='project_instances',
            field=models.PositiveIntegerField(default=4, help_text='Anzahl muss zwischen 1 und 99 liegen. Kann in den Projekteinstellungen je Projekt überschrieben werden.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Standardanzahl der Projektinstanzen'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='team_min_member',
            field=models.PositiveIntegerField(default=6, help_text='Anzahl muss zwischen 1 und 20 liegen.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Mindestanzahl der Studenten je Team'),
        ),
    ]
