# Generated by Django 5.2.5 on 2025-09-01 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_project_instances_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pid',
            field=models.CharField(help_text='Muss ein Großbuchstaben von A bis Z sein', max_length=1, unique=True, validators=[django.core.validators.RegexValidator('[A-Z]')], verbose_name='Projekt-ID'),
        ),
    ]
