# Generated by Django 5.2.5 on 2025-09-01 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_project_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.CharField(blank=True, help_text='Name der Firma, des Vereins oder der Hochschule mit Fakultät', max_length=255, null=True, verbose_name='Auftraggeber'),
        ),
        migrations.AlterField(
            model_name='project',
            name='instances',
            field=models.PositiveIntegerField(blank=True, help_text='Anzahl der Projektinstanzen (1-99) oder leer für Standardanzahl', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Instanzen'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pid',
            field=models.CharField(help_text='Aktuell limitiert auf Grossbuchstaben von A bis Z', max_length=1, unique=True, validators=[django.core.validators.RegexValidator('[A-Z]')], verbose_name='Projekt-ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, help_text='PDF oder Webseite zu den Projektbescheibungen', null=True, verbose_name='Link zu weiteren Informationen'),
        ),
    ]
