# Generated by Django 5.2.5 on 2025-09-08 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_project_company_alter_project_instances_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_random_poll_defaults', models.BooleanField(default=False, help_text='Wenn aktiv, werden leere Fragebögen nicht mit neutralen Antworten (3), sondern mit zufälligen Anworten (1-5) ausgefüllt.', verbose_name='Zufällige Anworten für leere Fragebögen generieren')),
                ('max_runtime', models.PositiveIntegerField(default=300, help_text='Anzahl muss zwischen 1 und 3600 liegen.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3600)], verbose_name='Maximale Laufzeit der Teamgenerierung')),
                ('level_variant', models.IntegerField(choices=[(0, 'Projektwünsche'), (1, 'Projektwünsche + Ambitionsniveau'), (2, '...')], verbose_name='Berechnungsvariante')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
