# Generated by Django 5.2.5 on 2025-09-09 08:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_extrasettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_runtime', models.PositiveIntegerField(default=300, help_text='Muss zwischen 1 und 3600 Sekunden liegen.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3600)], verbose_name='Maximale Laufzeit der Teamgenerierung in Sekunden')),
                ('level_variant', models.IntegerField(choices=[(0, 'Projektpräferenz'), (1, 'Projektpräferenz mit Gruppierung nach Ambitionsniveau'), (2, 'Projektpräferenz mit Einfluss des Ambitionsniveaus')], default=0, verbose_name='Teamgenerierungsvariante')),
                ('use_random_poll_defaults', models.BooleanField(default=False, help_text='Wenn aktiv, werden leere Fragebögen nicht mit neutralen Antworten (3), sondern mit zufälligen Anworten (1-5) ausgefüllt.', verbose_name='Zufällige Anworten für leere Fragebögen generieren')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ExtraSettings',
        ),
    ]
