# Generated by Django 5.2.5 on 2025-09-09 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_devsettings_delete_extrasettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='use_random_poll_defaults',
        ),
        migrations.AlterField(
            model_name='devsettings',
            name='level_variant',
            field=models.IntegerField(choices=[(1, 'Variante 1: Projektpräferenz'), (2, 'Variante 2: Projektpräferenz mit Gruppierung nach Ambitionsniveau'), (3, 'Variante 3: Projektpräferenz mit Einfluss des Ambitionsniveaus')], default=1, help_text='Variante 1: Die Teams werden mit einer möglichst hohen Zufriedenheit über alle Projektpräferenzen generiert.<br />Variante 2: Wie Variante 1, jedoch mit einer höher priorisierten Gruppierung nach Ambitionsniveau.<br />Variante 3: Wie Variante 1, jedoch mit Einfluss des Ambitionsniveaus auf die Projektpräferenzen.', verbose_name='Teamgenerierungsvariante'),
        ),
        migrations.AlterField(
            model_name='devsettings',
            name='max_runtime',
            field=models.PositiveIntegerField(default=300, help_text='Muss zwischen 1 und 3600 Sekunden liegen.<br />Dauert die Laufzeit länger als die angegeben Zeit, wird die Teamgenerierung abgebrochen.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3600)], verbose_name='Maximale Laufzeit der Teamgenerierung in Sekunden'),
        ),
    ]
