# Generated by Django 5.2.5 on 2025-09-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_info_result_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='devsettings',
            name='show_debug_info',
            field=models.BooleanField(default=False, help_text='Wenn aktiv, werden Debug-Informationen angezeigt.', verbose_name='Debug-Informationen anzeigen'),
        ),
    ]
