# Generated by Django 5.2.5 on 2025-09-11 08:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_devsettings_show_debug_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='devsettings',
            name='relative_gap_limit',
            field=models.FloatField(default=0.0, help_text='Muss zwischen 0 und 1 liegen.<br />Ist die Lösung nahe genug am optimalen Wert, wird die Teamgenerierung abgebrochen.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Akzeptierte Lösungsqualität/Verhältnis zwischen `objective_value` and `best_objective_bound`'),
        ),
    ]
