# Generated by Django 5.2.5 on 2025-09-11 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_devsettings_relative_gap_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='devsettings',
            name='num_workers',
            field=models.PositiveIntegerField(default=0, help_text='Muss zwischen 0 und 64 liegen.<br />Ein Angabe von 0 wählt eine CPU abhängige Anzahl der Suchprozesse.<br />Die Anzahl der Suchprozesse wird von OR-Tools verwendet, um die Lösung zu optimieren.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32)], verbose_name='OR-Tools: Anzahl der parallelen Suchprozesse'),
        ),
        migrations.AlterField(
            model_name='devsettings',
            name='level_variant',
            field=models.IntegerField(choices=[(1, 'Variante 1: Projektpräferenz'), (2, 'Variante 2: Projektpräferenz mit Gruppierung nach Ambitionsniveau'), (3, 'Variante 3: Projektpräferenz mit Einfluss des Ambitionsniveaus')], default=1, help_text='Variante 1: Die Teams werden mit einer möglichst hohen Zufriedenheit über alle Projektpräferenzen generiert.<br />Variante 2: Wie Variante 1, jedoch mit einer höher priorisierten Gruppierung nach Ambitionsniveau.<br />Variante 3: Wie Variante 1, jedoch mit Einfluss des Ambitionsniveaus auf die Projektpräferenzen.', verbose_name='OR-Tools: Teamgenerierungsvariante'),
        ),
        migrations.AlterField(
            model_name='devsettings',
            name='max_runtime',
            field=models.PositiveIntegerField(default=300, help_text='Muss zwischen 1 und 3600 Sekunden liegen.<br />Dauert die Laufzeit länger als die angegeben Zeit, wird die Teamgenerierung abgebrochen.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3600)], verbose_name='OR-Tools: Maximale Laufzeit der Teamgenerierung in Sekunden'),
        ),
        migrations.AlterField(
            model_name='devsettings',
            name='relative_gap_limit',
            field=models.FloatField(default=0.0, help_text='Muss zwischen 0 und 1 liegen.<br />Ist die Lösung nahe genug am optimalen Wert, wird die Teamgenerierung abgebrochen.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='OR-Tools: Akzeptierte Lösungsqualität/Verhältnis zwischen `objective_value` and `best_objective_bound`'),
        ),
    ]
