# Generated by Django 5.2.5 on 2025-09-12 05:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_devsettings_num_workers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devsettings',
            name='level_variant',
        ),
        migrations.AddField(
            model_name='devsettings',
            name='assignment_variant',
            field=models.IntegerField(choices=[(1, 'Variante 1: Projektpräferenz'), (2, 'Variante 2: Ambitionsniveau (wip)'), (3, 'Variante 3: Ambitionsniveau und Projektpräferenz (wip)'), (4, 'Variante 4: Projektpräferenz mit Einfluss des Ambitionsniveaus (wip)')], default=1, help_text='Variante 1: Die Teams werden mit einer möglichst hohen Zufriedenheit über alle Projektpräferenzen generiert.<br />Variante 2: Die Teams werden nach dem Ambitionsniveau gruppiert.<br />Variante 3: Wie Variante 1, jedoch mit einer höher priorisierten Gruppierung nach Ambitionsniveau.<br />Variante 4: Wie Variante 1, jedoch mit Einfluss des Ambitionsniveaus auf die Projektpräferenzen.<br />', verbose_name='Teamgenerierungsvariante'),
        ),
        migrations.AlterField(
            model_name='devsettings',
            name='num_workers',
            field=models.PositiveIntegerField(default=0, help_text='Muss zwischen 0 und 64 liegen.<br />- A value of 0 means the solver will try to use all cores on the machine.<br />- A number of 1 means no parallelism.<br />Specify the number of parallel workers (i.e. threads) to use during search.<br />This should usually be lower than your number of available cpus + hyperthread in your machine.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(64)], verbose_name='OR-Tools: Anzahl der parallelen Suchprozesse'),
        ),
    ]
