# Generated by Django 5.2.6 on 2025-09-15 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_devsettings_level_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devsettings',
            name='assignment_variant',
            field=models.IntegerField(choices=[(1, 'Variante 1: Projektpräferenz'), (2, 'Variante 2: Ambitionsniveau (wip)'), (3, 'Variante 3: Ambitionsniveau und Projektpräferenz (wip)')], default=1, help_text='Variante 1: Die Teams werden mit einer möglichst hohen Zufriedenheit über alle Projektpräferenzen generiert.<br />Variante 2: Die Teams werden nach dem Ambitionsniveau gruppiert.<br />Variante 3: Wie Variante 1, jedoch mit einer höher priorisierten Gruppierung nach Ambitionsniveau.', verbose_name='Teamgenerierungsvariante'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='team_min_member',
            field=models.PositiveIntegerField(default=6, help_text='Anzahl muss zwischen 1 und 99 liegen.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Mindestanzahl der Studenten je Team'),
        ),
    ]
