# Generated by Django 6.0.3 on 2026-04-28 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_devsettings_assignment_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devsettings',
            name='max_runtime',
            field=models.PositiveIntegerField(default=300, help_text='Muss zwischen 1 und 3600 Sekunden liegen.<br />Dauert die Laufzeit länger als die angegeben Zeit, wird die Teamgenerierung abgebrochen.<br /><span class="text-danger">Achtung: In der Dockerumgebung ist die maximale Laufzeit auf unter 300 Sekunden limitiert.</span>', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3600)], verbose_name='OR-Tools: Maximale Laufzeit der Teamgenerierung in Sekunden'),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_number',
            field=models.CharField(max_length=8, unique=True, verbose_name='s-Nummer'),
        ),
    ]
