# Generated by Django 6.0.3 on 2026-05-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_devsettings_max_runtime_alter_student_s_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='feedback_is_visible',
            field=models.BooleanField(default=False, help_text='Wenn aktiv, ist der Feedback-Fragebogen für die Studenten sichtbar.', verbose_name='Feedback anzeigen'),
        ),
    ]
