# Generated by Django 6.0.3 on 2026-05-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_settings_feedback_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='feedback_is_writable',
            field=models.BooleanField(default=False, help_text='Wenn aktiv, kann der Feedback-Fragebogen von den Studenten beantwortet bzw. geändert und abgesendet werden.', verbose_name='Feedback-Fragebogen is ausfüllbar (schreibbar)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='feedback_is_visible',
            field=models.BooleanField(default=False, help_text='Wenn aktiv, ist der Feedback-Fragebogen für die Studenten sichtbar.', verbose_name='Feedback-Fragebogen anzeigen'),
        ),
    ]
