# Generated by Django 6.0.3 on 2026-05-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_settings_feedback_is_visible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='peer_feedback_1_is_visible',
            field=models.BooleanField(default=False, help_text='Wenn aktiv, ist der Fragebogen für die Studenten sichtbar.', verbose_name='SE I Peer-Feedback Fragebogen anzeigen'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='peer_feedback_1_is_writable',
            field=models.BooleanField(default=False, help_text='Wenn aktiv, kann der Fragebogen von den Studenten beantwortet bzw. geändert und abgesendet werden.', verbose_name='SE I Peer-Feedback Fragebogen is ausfüllbar (schreibbar)'),
        ),
    ]
